# Generated by Django 4.0.5 on 2022-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email адрес')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Имя пользователя')),
                ('image', models.ImageField(upload_to='users/images', verbose_name='Аватар пользователя')),
                ('type', models.CharField(default='player', max_length=64, verbose_name='Тип аккаунта')),
                ('age', models.IntegerField(verbose_name='Возраст пользователя')),
                ('levels', models.IntegerField(verbose_name='Количество пройденных уровней')),
                ('scores', models.IntegerField(verbose_name='Набранные очки пользователем')),
                ('money', models.IntegerField(verbose_name='Внутриигровая валюта')),
                ('diamonds', models.IntegerField(verbose_name='Внутриигровая валюта')),
                ('is_activ', models.BooleanField(default=False, verbose_name='')),
                ('is_staff', models.BooleanField(default=False, verbose_name='')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
