# Generated by Django 4.0.5 on 2022-06-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
