# Generated by Django 4.0.5 on 2022-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_usermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email адрес'),
        ),
    ]
