# Generated by Django 4.0.5 on 2022-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_age_alter_user_diamonds_alter_user_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diamonds',
            field=models.IntegerField(default=0, verbose_name='Внутриигровая валюта Алмазы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Внутриигровая валюта Монеты'),
        ),
    ]
