# Generated by Django 4.0.5 on 2022-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_diamonds_alter_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
