# Generated by Django 4.0.6 on 2022-07-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_is_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/images/KnightAvatar.jpeg', upload_to='users/images', verbose_name='Аватар пользователя'),
        ),
    ]
