# Generated by Django 4.0.5 on 2022-06-19 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('description', models.TextField(verbose_name='Описание уровня')),
                ('difficulty', models.IntegerField(verbose_name='Сложность уровня')),
                ('reward', models.IntegerField(verbose_name='Награда за прохождение уровня')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Пейзаж уровня')),
                ('best_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
    ]
