# Generated by Django 4.0.5 on 2022-06-20 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enemies', '0002_enemy_delete_enemies'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
    ]
