# Generated by Django 4.0.5 on 2022-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_rename_levels_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.CharField(max_length=255, verbose_name='Сложность уровня'),
        ),
    ]
