# Generated by Django 4.0.5 on 2022-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_level_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(upload_to='levels/images', verbose_name='Пейзаж уровня'),
        ),
    ]
