# Generated by Django 4.0.5 on 2022-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя врага')),
                ('description', models.TextField(verbose_name='Описание врага')),
                ('hp', models.IntegerField(verbose_name='Здоровье врага')),
                ('power', models.IntegerField(verbose_name='Сила вражеской атаки')),
                ('difficulty', models.IntegerField(verbose_name='Сложность вражеских атак')),
                ('reward', models.IntegerField(verbose_name='Награда за убийство')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Портрет врага')),
                ('level_id', models.ManyToManyField(related_name='enemy', to='levels.level', verbose_name='Присутствие в эпизодах')),
            ],
            options={
                'verbose_name': 'Враг',
                'verbose_name_plural': 'Враги',
            },
        ),
        migrations.DeleteModel(
            name='Enemies',
        ),
    ]
