# Generated by Django 4.0.5 on 2022-06-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0002_enemy_delete_enemies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='level_id',
        ),
    ]
