# Generated by Django 4.0.5 on 2022-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_rename_levels_level'),
        ('enemies', '0003_remove_enemy_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='level_id',
            field=models.ManyToManyField(blank=True, related_name='enemy', to='levels.level'),
        ),
    ]
