# Generated by Django 4.0.5 on 2022-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0004_enemy_level_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='level_id',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='difficulty',
            field=models.CharField(max_length=255, verbose_name='Сложность вражеских атак'),
        ),
    ]
