# Generated by Django 4.0.5 on 2022-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0005_rename_level_id_enemy_level_alter_enemy_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='image',
            field=models.ImageField(upload_to='enemies/images', verbose_name='Портрет врага'),
        ),
    ]
