# Generated by Django 4.0.5 on 2022-06-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0004_alter_level_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия достижения')),
                ('description', models.TextField(verbose_name='Описание достижения')),
                ('diamonds', models.IntegerField(verbose_name='Награда за достижение')),
                ('image', models.ImageField(upload_to='achievements/images', verbose_name='Иллюстрация достижения')),
                ('level', models.ManyToManyField(blank=True, related_name='achievement', to='levels.level')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
